"""Generate tenant module update offers from version drift."""

from __future__ import annotations

import re
from datetime import datetime

from sqlalchemy.orm import Session

from app.modules.platform_modules.version_crud import get_latest_module_version
from app.modules.platform_modules.version_models import PlatformReleaseModule
from app.modules.tenant_module_update_offers import crud
from app.modules.tenant_module_update_offers.constants import (
    GENERATOR_SOURCE,
    TenantModuleUpdateOfferStatus,
)
from app.modules.tenant_module_update_offers.models import TenantModuleUpdateOffer
from app.modules.tenant_modules import crud as tenant_modules_crud
from app.modules.tenant_modules.models import TenantModule


def _version_sort_key(version: str) -> tuple[int, int, int, str]:
    match = re.match(r"^(\d+)\.(\d+)\.(\d+)(.*)$", str(version or "0.0.0"))
    if not match:
        return (0, 0, 0, str(version))
    major, minor, patch, suffix = match.groups()
    return (int(major), int(minor), int(patch), suffix)


def is_version_less(left: str, right: str) -> bool:
    return _version_sort_key(left) < _version_sort_key(right)


def _split_change_summary(summary: str | None) -> list[str]:
    if not summary:
        return []
    items: list[str] = []
    for line in str(summary).splitlines():
        normalized = line.strip().lstrip("-").strip()
        if normalized:
            items.append(normalized)
    return items


def _aggregate_change_summary(summaries: list[str | None]) -> str | None:
    items: list[str] = []
    seen: set[str] = set()
    for summary in summaries:
        for item in _split_change_summary(summary):
            if item not in seen:
                seen.add(item)
                items.append(item)
    if not items:
        return None
    return "\n".join(f"- {item}" for item in items)


def find_upgrade_release_modules(
    db: Session,
    *,
    module_key: str,
    from_version: str,
    to_version: str,
) -> list[PlatformReleaseModule]:
    rows = (
        db.query(PlatformReleaseModule)
        .filter(PlatformReleaseModule.module_key == module_key)
        .all()
    )
    if not rows:
        return []

    current = from_version
    path: list[PlatformReleaseModule] = []
    visited: set[str] = {current}

    while is_version_less(current, to_version):
        candidates = [
            row
            for row in rows
            if row.from_version == current and is_version_less(current, row.to_version)
        ]
        if not candidates:
            break

        step = max(candidates, key=lambda row: _version_sort_key(row.to_version))
        if _version_sort_key(step.to_version) > _version_sort_key(to_version):
            break

        path.append(step)
        current = step.to_version
        if current in visited:
            break
        visited.add(current)

    if current != to_version:
        direct = [
            row
            for row in rows
            if row.from_version == from_version and row.to_version == to_version
        ]
        if direct:
            return [direct[0]]

    return path


def build_offer_payload_for_tenant_module(
    db: Session,
    tenant_module: TenantModule,
) -> dict | None:
    latest = get_latest_module_version(db, tenant_module.module_key)
    if latest is None:
        return None

    installed_version = str(tenant_module.installed_version or "1.0.0")
    latest_version = str(latest.version or installed_version)

    if not is_version_less(installed_version, latest_version):
        return None

    upgrade_path = find_upgrade_release_modules(
        db,
        module_key=tenant_module.module_key,
        from_version=installed_version,
        to_version=latest_version,
    )

    release_id = upgrade_path[-1].release_id if upgrade_path else latest.release_id
    change_summary = _aggregate_change_summary([row.change_summary for row in upgrade_path])

    if not change_summary and upgrade_path:
        change_summary = upgrade_path[-1].change_summary

    return {
        "tenant_id": tenant_module.tenant_id,
        "module_key": tenant_module.module_key,
        "from_version": installed_version,
        "to_version": latest_version,
        "release_id": release_id,
        "change_summary": change_summary,
        "notes": f"Generated by {GENERATOR_SOURCE}",
    }


def _regenerate_preview_after_offer_change(db: Session, offer, *, withdrawn_offer_ids=None) -> None:
    from app.modules.tenant_module_update_previews.generator import regenerate_preview_after_offer_change

    regenerate_preview_after_offer_change(
        db,
        offer,
        withdrawn_offer_ids=withdrawn_offer_ids,
        commit=False,
    )


def generate_offer_for_tenant_module(
    db: Session,
    tenant_module: TenantModule,
    *,
    commit: bool = False,
) -> dict[str, int | str | None]:
    payload = build_offer_payload_for_tenant_module(db, tenant_module)
    now = datetime.utcnow()

    if payload is None:
        withdrawn_rows = (
            db.query(TenantModuleUpdateOffer)
            .filter(
                TenantModuleUpdateOffer.tenant_id == tenant_module.tenant_id,
                TenantModuleUpdateOffer.module_key == tenant_module.module_key,
                TenantModuleUpdateOffer.status == TenantModuleUpdateOfferStatus.AVAILABLE,
            )
            .all()
        )
        withdrawn_offer_ids = [row.id for row in withdrawn_rows]
        withdrawn = crud.withdraw_available_offers_for_module(
            db,
            tenant_id=tenant_module.tenant_id,
            module_key=tenant_module.module_key,
        )
        _regenerate_preview_after_offer_change(
            db,
            None,
            withdrawn_offer_ids=withdrawn_offer_ids,
        )
        if commit:
            db.commit()
        return {"created": 0, "updated": 0, "withdrawn": withdrawn, "skipped": 1}

    existing = crud.get_available_offer_for_module(
        db,
        tenant_id=tenant_module.tenant_id,
        module_key=tenant_module.module_key,
    )

    if existing is None:
        db.add(
            TenantModuleUpdateOffer(
                tenant_id=payload["tenant_id"],
                module_key=payload["module_key"],
                from_version=payload["from_version"],
                to_version=payload["to_version"],
                release_id=payload["release_id"],
                status=TenantModuleUpdateOfferStatus.AVAILABLE,
                offered_at=now,
                change_summary=payload["change_summary"],
                notes=payload["notes"],
                created_at=now,
                updated_at=now,
            )
        )
        db.flush()
        created_offer = crud.get_available_offer_for_module(
            db,
            tenant_id=tenant_module.tenant_id,
            module_key=tenant_module.module_key,
        )
        if created_offer is not None:
            _regenerate_preview_after_offer_change(db, created_offer)
        if commit:
            db.commit()
        return {"created": 1, "updated": 0, "withdrawn": 0, "skipped": 0}

    changed = False
    for field in ("from_version", "to_version", "release_id", "change_summary", "notes"):
        if getattr(existing, field) != payload[field]:
            setattr(existing, field, payload[field])
            changed = True

    if changed:
        existing.offered_at = now
        existing.updated_at = now
        db.flush()
        _regenerate_preview_after_offer_change(db, existing)
        if commit:
            db.commit()
        return {"created": 0, "updated": 1, "withdrawn": 0, "skipped": 0}

    if commit:
        db.commit()
    return {"created": 0, "updated": 0, "withdrawn": 0, "skipped": 1}


def generate_offers_for_tenant(
    db: Session,
    tenant_id: int,
    *,
    commit: bool = False,
) -> dict[str, int]:
    totals = {"created": 0, "updated": 0, "withdrawn": 0, "skipped": 0, "modules": 0}

    for tenant_module in tenant_modules_crud.list_tenant_modules(db, tenant_id):
        result = generate_offer_for_tenant_module(db, tenant_module, commit=False)
        totals["created"] += int(result["created"])
        totals["updated"] += int(result["updated"])
        totals["withdrawn"] += int(result["withdrawn"])
        totals["skipped"] += int(result["skipped"])
        totals["modules"] += 1

    db.flush()
    if commit:
        db.commit()

    return totals


def generate_offers_for_all_tenants(
    db: Session,
    *,
    tenant_ids: list[int] | None = None,
    commit: bool = True,
) -> dict[str, int]:
    from app.modules.portals.models import Portal

    query = db.query(Portal.id)
    if tenant_ids:
        query = query.filter(Portal.id.in_(tenant_ids))

    totals = {"created": 0, "updated": 0, "withdrawn": 0, "skipped": 0, "tenants": 0}

    for (portal_id,) in query.order_by(Portal.id.asc()).all():
        result = generate_offers_for_tenant(db, portal_id, commit=False)
        totals["created"] += result["created"]
        totals["updated"] += result["updated"]
        totals["withdrawn"] += result["withdrawn"]
        totals["skipped"] += result["skipped"]
        totals["tenants"] += 1

    db.flush()
    if commit:
        db.commit()

    return totals
