"""Canonical architecture catalog seed (WI-ARCH-02 synthesis)."""

from __future__ import annotations

from app.modules.platform.architecture_navigator.constants import (
    ArchitectureComponentType,
    ArchitectureLinkType,
    ArchitectureSourceKind,
)

CatalogComponent = dict
CatalogLink = dict

CATALOG_COMPONENTS: list[CatalogComponent] = [
    # --- Контуры ---
    {
        "component_key": "control-plane",
        "technical_name": "Control Plane",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Контур управления платформой",
        "description": "Глобальное управление жизненным циклом платформы, компаниями и релизами.",
        "purpose": "Управление жизненным циклом платформы",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "dev-environment",
        "technical_name": "DEV",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Среда разработки",
        "description": "Рабочая среда проектирования метаданных и платформенных артефактов.",
        "purpose": "Проектирование и отладка структуры платформы",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "template-environment",
        "technical_name": "TEMPLATE",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Эталонная среда",
        "description": "Эталонная публикация структуры для тиражирования в клиентские компании.",
        "purpose": "Канонический шаблон для CLIENT tenant",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "client-environment",
        "technical_name": "CLIENT",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Клиентские компании",
        "description": "Рабочие tenant компаний с изолированными бизнес-данными.",
        "purpose": "Эксплуатация платформы конечными организациями",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Подсистемы ---
    {
        "component_key": "studio",
        "technical_name": "Studio",
        "component_type": ArchitectureComponentType.SUBSYSTEM.value,
        "category_key": "subsystems",
        "title": "Конструктор платформы",
        "description": "Режим проектирования объектов, страниц, процессов и публикаций.",
        "purpose": "Проектирование метаданных и структуры портала",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "office",
        "technical_name": "Office",
        "component_type": ArchitectureComponentType.SUBSYSTEM.value,
        "category_key": "subsystems",
        "title": "Рабочее пространство",
        "description": "Пользовательский режим работы с данными, задачами и процессами.",
        "purpose": "Операционная работа пользователей tenant",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "tenant-administration",
        "technical_name": "Tenant Administration",
        "component_type": ArchitectureComponentType.SUBSYSTEM.value,
        "category_key": "subsystems",
        "title": "Администрирование компании",
        "description": "Управление пользователями, ролями и настройками конкретного tenant.",
        "purpose": "Администрирование внутри границ компании",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Ядро ---
    {
        "component_key": "entity-engine",
        "technical_name": "Entity Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок объектов",
        "description": "Источник истины бизнес-данных tenant: записи объектов и их версии.",
        "purpose": "Хранение и доступ к данным объектов",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "relation-engine",
        "technical_name": "Relation Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок связей",
        "description": "Связи между экземплярами объектов по опубликованным определениям.",
        "purpose": "Связывание сущностей в графе данных",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "event-engine",
        "technical_name": "Event Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок событий",
        "description": "Журналы событий, аудит и dev-development записи.",
        "purpose": "Фиксация значимых изменений и событий",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "process-engine",
        "technical_name": "Process Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок процессов",
        "description": "Исполнение бизнес-процессов поверх объектов и действий.",
        "purpose": "Оркестрация бизнес-процессов",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "action-engine",
        "technical_name": "Action Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок действий",
        "description": "Определения действий, формы и размещения в UI.",
        "purpose": "Пользовательские и системные действия над данными",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "ai-context-engine",
        "technical_name": "AI Context Service",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Служба контекста ИИ",
        "description": (
            "Сбор и нормализация контекста для ЯСИИ: HostContext, PermissionBoundary, handoff."
        ),
        "purpose": "Безопасный контекст для встроенного ИИ-сотрудника",
        "parent_key": None,
        "sort_order": 90,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Платформенные компоненты ---
    {
        "component_key": "platform-modal",
        "technical_name": "PlatformModal",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Модальное окно платформы",
        "description": "Стандартное модальное окно с drag, resize и persist bounds (Platform Modal Standard).",
        "purpose": "Единообразные панели настроек и диалоги",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-page",
        "technical_name": "PlatformPage",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Страница платформы",
        "description": "Каркас страницы Studio/Office с контрактом layout и зонами toolbar.",
        "purpose": "Единая структура экранов платформы",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-table",
        "technical_name": "PlatformTable",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Таблица платформы",
        "description": "Табличное представление данных объектов с фильтрами и настройками вида.",
        "purpose": "Отображение и работа со списками записей",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-form",
        "technical_name": "PlatformForm",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Форма платформы",
        "description": "Стандартная форма редактирования полей объекта и действий.",
        "purpose": "Ввод и редактирование данных",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-tree",
        "technical_name": "PlatformTree",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Дерево платформы",
        "description": "Иерархическое дерево навигации и структуры (sidebar, object tree).",
        "purpose": "Навигация по иерархии",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-card",
        "technical_name": "PlatformCard",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Карточка платформы",
        "description": "Контейнер детальной информации с секциями и полями.",
        "purpose": "Просмотр и редактирование сущности",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-tabs",
        "technical_name": "PlatformTabs",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Вкладки платформы",
        "description": "Переключение представлений и рабочих зон внутри страницы.",
        "purpose": "Организация контента по вкладкам",
        "parent_key": None,
        "sort_order": 70,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-drawer",
        "technical_name": "PlatformDrawer",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Выдвижная панель",
        "description": "Боковая панель для контекстных действий и деталей.",
        "purpose": "Контекстные панели без смены страницы",
        "parent_key": None,
        "sort_order": 80,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-toolbar",
        "technical_name": "PlatformToolbar",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Панель инструментов",
        "description": "Зона действий страницы: кнопки, фильтры, контекстные команды.",
        "purpose": "Действия и инструменты на уровне экрана",
        "parent_key": None,
        "sort_order": 90,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-notification",
        "technical_name": "PlatformNotification",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Уведомление платформы",
        "description": "Компонент отображения уведомлений и toast-сообщений.",
        "purpose": "Обратная связь и оповещения пользователю",
        "parent_key": None,
        "sort_order": 100,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-sidebar",
        "technical_name": "PlatformSidebar",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Боковая панель платформы",
        "description": "Primary navigation shell: collapse, mode switcher, menu host.",
        "purpose": "Строительный блок элемента «Боковое меню»",
        "parent_key": None,
        "sort_order": 110,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-breadcrumbs",
        "technical_name": "PlatformBreadcrumbs",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Хлебные крошки платформы",
        "description": "Orientation chain in app header from page layout contract.",
        "purpose": "Строительный блок элемента «Хлебные крошки»",
        "parent_key": None,
        "sort_order": 120,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-context-menu",
        "technical_name": "PlatformContextMenu",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Контекстное меню платформы",
        "description": "Context commands for selected object, row, or zone.",
        "purpose": "Строительный блок элемента «Контекстное меню»",
        "parent_key": None,
        "sort_order": 130,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "user-picker",
        "technical_name": "UserPicker",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Выбор пользователя",
        "description": "Domain picker for user, assignee, and membership fields.",
        "purpose": "Строительный блок picker-panel для пользователей",
        "parent_key": None,
        "sort_order": 140,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "object-picker",
        "technical_name": "ObjectPicker",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Выбор объекта",
        "description": "Lookup and relation picker for linked object records.",
        "purpose": "Строительный блок picker-panel для связей",
        "parent_key": None,
        "sort_order": 150,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "file-picker",
        "technical_name": "FilePicker",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Выбор файла",
        "description": "Attachment and file field picker integrated with file storage.",
        "purpose": "Строительный блок picker-panel для файлов",
        "parent_key": None,
        "sort_order": 160,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-kanban",
        "technical_name": "PlatformKanban",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Канбан платформы",
        "description": "View Type Renderer for board view (view_type=board).",
        "purpose": "Член семейства View Type Renderer",
        "parent_key": None,
        "sort_order": 170,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-calendar",
        "technical_name": "PlatformCalendar",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Календарь платформы",
        "description": "View Type Renderer for calendar view (view_type=calendar).",
        "purpose": "Член семейства View Type Renderer; отличен от calendar-module",
        "parent_key": None,
        "sort_order": 180,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Платформенные элементы интерфейса (WI-ARCH-REG-UI-002: 20 elements) ---
    {
        "component_key": "side-navigation",
        "technical_name": "Side Navigation",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Боковое меню",
        "description": "Sidebar с деревом разделов Studio/Office.",
        "purpose": "Основная навигация по разделам tenant",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "top-navigation",
        "technical_name": "Top Navigation",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Верхняя панель",
        "description": "App header: бренд, поиск, уведомления, профиль.",
        "purpose": "Глобальная навигация и действия",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "breadcrumbs",
        "technical_name": "Breadcrumbs",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Хлебные крошки",
        "description": "Цепочка навигации текущего контекста страницы.",
        "purpose": "Ориентация в иерархии разделов",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "avatar",
        "technical_name": "Avatar",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Аватар пользователя",
        "description": "Отображение фото/инициалов пользователя в оболочке платформы.",
        "purpose": "Визуальная идентификация пользователя",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "user-menu",
        "technical_name": "User Menu",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Меню пользователя",
        "description": "Выпадающее меню профиля, выхода и персональных действий.",
        "purpose": "Доступ к профилю и сессии",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "global-search",
        "technical_name": "Global Search",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Глобальный поиск",
        "description": "Единый поиск по runtime и designer из header платформы.",
        "purpose": "Быстрый поиск сущностей и страниц",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "notification-center",
        "technical_name": "Notification Center",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Центр уведомлений",
        "description": "Колокол и overlay со списком непрочитанных уведомлений пользователя.",
        "purpose": "Агрегированный доступ к уведомлениям платформы",
        "parent_key": None,
        "sort_order": 70,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "settings-entry",
        "technical_name": "Settings Entry",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Точка входа в настройки",
        "description": "Точка входа в настройки страницы, вида, workspace или пользователя.",
        "purpose": "Быстрый доступ к настройкам контекста",
        "parent_key": None,
        "sort_order": 80,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "workspace-tabs",
        "technical_name": "Workspace Tabs",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Вкладки рабочей области",
        "description": "Multi-tab полоса открытых страниц и разделов в workspace.",
        "purpose": "Переключение между открытыми местами работы",
        "parent_key": None,
        "sort_order": 90,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "favorites-recent",
        "technical_name": "Favorites and Recent",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Избранное и недавние",
        "description": "Списки закладок и недавно открытых разделов, страниц и объектов.",
        "purpose": "Быстрый доступ к частым и последним местам работы",
        "parent_key": None,
        "sort_order": 100,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "context-switcher",
        "technical_name": "Context Switcher",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Переключатель контекста",
        "description": "Смена tenant, режима Studio/Office/CP и рабочего контекста.",
        "purpose": "Явная зона смены контекста работы",
        "parent_key": None,
        "sort_order": 110,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "entity-card",
        "technical_name": "Entity Card",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Карточка объекта",
        "description": "Экран детальной работы с одной записью объекта.",
        "purpose": "Primary surface просмотра и редактирования записи",
        "parent_key": None,
        "sort_order": 120,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "view-surface",
        "technical_name": "View Surface",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Поверхность представления",
        "description": "Host для таблицы, дерева, плана и других view types над коллекцией записей.",
        "purpose": "Рабочая зона списков и представлений объекта",
        "parent_key": None,
        "sort_order": 130,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "action-panel",
        "technical_name": "Action Panel",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Панель действий",
        "description": "Зона команд над объектом, списком или экраном.",
        "purpose": "Discoverability действий пользователя",
        "parent_key": None,
        "sort_order": 140,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "properties-panel",
        "technical_name": "Properties Panel",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Панель свойств",
        "description": "Боковая или встроенная зона свойств выбранного объекта или контекста.",
        "purpose": "Детали выбранного без полной карточки",
        "parent_key": None,
        "sort_order": 150,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "modal-zone",
        "technical_name": "Modal Zone",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Модальная зона",
        "description": "Overlay для форм, настроек, подтверждений поверх основного экрана.",
        "purpose": "Стандартный UX-контур вторичных задач",
        "parent_key": None,
        "sort_order": 160,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "side-panel",
        "technical_name": "Side Panel",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Боковая панель",
        "description": "Выезжающая или закреплённая боковая зона: фильтры, профиль, детали.",
        "purpose": "Вторичные формы без полного modal",
        "parent_key": None,
        "sort_order": 170,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "context-menu",
        "technical_name": "Context Menu",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Контекстное меню",
        "description": "Действия по контексту: правый клик, «⋯» на строке или объекте.",
        "purpose": "Контекстные команды над выделенным элементом",
        "parent_key": None,
        "sort_order": 180,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "quick-create",
        "technical_name": "Quick Create",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Быстрое создание",
        "description": "Compact form или wizard для новой записи без полной карточки.",
        "purpose": "Быстрое создание записи",
        "parent_key": None,
        "sort_order": 190,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "picker-panel",
        "technical_name": "Picker Panel",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Панель выбора",
        "description": "Picker / lookup UI для выбора связанной записи, пользователя или значения.",
        "purpose": "Сценарий «выбрать из…»",
        "parent_key": None,
        "sort_order": 200,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Модули (WI-ARCH-REG-MOD-002: 6 platform modules) ---
    {
        "component_key": "chats-module",
        "technical_name": "Chats Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "Чат",
        "description": "Корпоративный обмен сообщениями внутри компании.",
        "purpose": "Обмен сообщениями между пользователями tenant",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "calendar-module",
        "technical_name": "Calendar Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "Календарь",
        "description": "Планирование событий компании: встречи, сроки, участники.",
        "purpose": "Планирование и отображение событий",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "document-libraries-module",
        "technical_name": "Document Libraries Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "Документы",
        "description": "Хранение, просмотр и совместная работа с файлами компании.",
        "purpose": "Документооборот tenant",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "notifications-module",
        "technical_name": "Notifications Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "Уведомления",
        "description": "Центр уведомлений пользователя: колокол, список событий, настройки.",
        "purpose": "Пользовательский модуль уведомлений платформы",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "module-bpmn",
        "technical_name": "BPMN Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "BPMN",
        "description": "Визуальный редактор бизнес-процессов в Studio.",
        "purpose": "BPMN-диаграммы и моделирование процессов",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "module-yasii",
        "technical_name": "YASII Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "ЯСИИ",
        "description": "Встроенный интеллектуальный помощник платформы.",
        "purpose": "AI-сотрудник платформы для пользователей tenant",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Службы (WI-ARCH-REG-SERV-002: 9 platform services) ---
    {
        "component_key": "platform-identity",
        "technical_name": "Platform Identity Service",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Идентичность платформы",
        "description": (
            "Глобальная идентичность платформы: platform owner, глобальные пользователи, "
            "вход до выбора компании."
        ),
        "purpose": "Идентификация на уровне платформы",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "session-bridge",
        "technical_name": "Session Bridge",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Мост сессий",
        "description": (
            "Связь идентичности пользователя с рабочей средой компании без смешения "
            "контуров DEV, TEMPLATE и CLIENT."
        ),
        "purpose": "Безопасная авторизация между контурами",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "company-provisioning",
        "technical_name": "Company Provisioning",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Создание компании",
        "description": (
            "Создание новой CLIENT-компании: изолированная база, tenant, первый администратор, "
            "baseline версии."
        ),
        "purpose": "Lifecycle создания клиентской компании",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "publication-service",
        "technical_name": "Publication Service",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Служба публикации",
        "description": (
            "Исполнение переноса спроектированной структуры между средами: "
            "DEV → TEMPLATE → CLIENT."
        ),
        "purpose": "Тиражирование структуры между средами",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "deployment-execution",
        "technical_name": "Deployment Execution Service",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Исполнение развёртывания",
        "description": (
            "Выполнение фаз развёртывания пакета: verify, activate, rollback на уровне runtime."
        ),
        "purpose": "Оркестрация физического apply изменений",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "file-service",
        "technical_name": "File Service",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Файловая служба",
        "description": (
            "Хранение и выдача файлов: вложения, аватары, медиа модулей — "
            "единая инфраструктура загрузки."
        ),
        "purpose": "Единая политика хранения и доступа к файлам",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "search-service",
        "technical_name": "Search Service",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Поиск",
        "description": "Сквозной поиск по объектам, навигации и записям платформы.",
        "purpose": "Единая точка discovery",
        "parent_key": None,
        "sort_order": 70,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "notification-dispatch",
        "technical_name": "Notification Dispatch Service",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Доставка уведомлений",
        "description": (
            "Доставка уведомлений пользователям: in-app, email, push — "
            "транспорт и маршрутизация."
        ),
        "purpose": "Единый канал доставки уведомлений",
        "parent_key": None,
        "sort_order": 80,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "release-governance",
        "technical_name": "Release Governance",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Управление релизами",
        "description": "Legacy pipeline релизов; заменён Publication + Deployment Execution.",
        "purpose": "Архивный элемент governance",
        "parent_key": None,
        "sort_order": 100,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Данные (WI-ARCH-REG-DATA-002) ---
    {
        "component_key": "structure-metadata-data",
        "technical_name": "Structure Metadata",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Метаданные структуры",
        "description": "Метаданные конструктора и опубликованная структура компании: объекты, поля, связи, представления, действия.",
        "purpose": "Design-time и runtime-canonical описание структуры tenant",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "business-records-data",
        "technical_name": "Business Records",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Бизнес-записи",
        "description": "Экземпляры объектов tenant: проекты, задачи, клиенты и другие business records.",
        "purpose": "Основные данные компании в runtime",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "relation-instances-data",
        "technical_name": "Relation Instances",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Экземпляры связей",
        "description": "Связи между business records по опубликованным relation definitions.",
        "purpose": "Граф отношений между записями tenant",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "users-access-data",
        "technical_name": "Users and Access",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Пользователи и права доступа",
        "description": "Глобальные и platform users, membership, роли и effective permissions как хранимая модель.",
        "purpose": "Идентификационная и авторизационная информация",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "tenant-configuration-data",
        "technical_name": "Tenant Configuration",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Настройки компании",
        "description": "Tenant-scoped configuration: брендинг, модули, параметры портала и безопасности.",
        "purpose": "Параметры компании, не бизнес-записи",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "user-settings-data",
        "technical_name": "User Settings",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Пользовательские настройки",
        "description": "User-scoped settings, preferences и персонализация workspace.",
        "purpose": "Персональные параметры пользователя",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "module-domain-data",
        "technical_name": "Module Domain Data",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Данные модулей",
        "description": "Доменные данные платформенных модулей: чат, календарь, документы, уведомления, BPMN, ЯСИИ.",
        "purpose": "Содержимое модулей, не конструктор объектов",
        "parent_key": None,
        "sort_order": 70,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-catalog-data",
        "technical_name": "Platform Catalog",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Платформенный каталог",
        "description": "Master data Control Plane: компании, каталог модулей, platform roles и registry rows.",
        "purpose": "Платформенные справочники и реестры CP",
        "parent_key": None,
        "sort_order": 80,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "release-operations-data",
        "technical_name": "Release and Operations Data",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Данные публикации и эксплуатации",
        "description": "Release packages, scope, deployments, provenance и операционное состояние сред.",
        "purpose": "Lifecycle платформы и трассируемость доставки",
        "parent_key": None,
        "sort_order": 90,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "journals-data",
        "technical_name": "Journals",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Журналы",
        "description": "Platform audit, tenant event и DEV development journals — append-only записи.",
        "purpose": "Хранилище аудита, событий и dev-разработки",
        "parent_key": None,
        "sort_order": 100,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "file-metadata-data",
        "technical_name": "File Metadata",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Метаданные файлов",
        "description": "Структурированная информация о файлах: ссылки, версии, права, привязка к объектам и модулям.",
        "purpose": "Модель файлов без бинарного содержимого",
        "parent_key": None,
        "sort_order": 110,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Решения / принципы (WI-ARCH-REG-STD-002: standards_registry_catalog.py) ---
    # --- Запреты ---
    {
        "component_key": "restriction-no-tenant-data-in-control-plane",
        "technical_name": "No Tenant Business Data in Control Plane",
        "component_type": ArchitectureComponentType.ARCHITECTURE_RESTRICTION.value,
        "category_key": "restrictions",
        "title": "Не хранить бизнес-данные компаний в Control Plane",
        "description": "Control Plane управляет платформой, не хранит клиентские записи.",
        "purpose": "Изоляция контуров",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "restriction-no-display-as-id",
        "technical_name": "No Display Fields as Identifiers",
        "component_type": ArchitectureComponentType.ARCHITECTURE_RESTRICTION.value,
        "category_key": "restrictions",
        "title": "Не использовать title/name как идентификатор",
        "description": "Идентификация только через id, key, code и стабильные технические поля.",
        "purpose": "Стабильность ссылок и защиты",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "restriction-runtime-no-designer-draft",
        "technical_name": "Runtime Must Not Read Designer Draft",
        "component_type": ArchitectureComponentType.ARCHITECTURE_RESTRICTION.value,
        "category_key": "restrictions",
        "title": "Runtime не читает черновик designer",
        "description": "Runtime использует только Published Catalog.",
        "purpose": "Разделение проектирования и эксплуатации",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
]

CATALOG_LINKS: list[CatalogLink] = [
    # --- Services / configuration (WI-ARCH-LINKS-001: no legacy runtime contours) ---
    {"from": "company-provisioning", "to": "publication-service", "type": ArchitectureLinkType.USES.value},
    {"from": "publication-service", "to": "deployment-execution", "type": ArchitectureLinkType.USES.value},
    {"from": "session-bridge", "to": "ai-context-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "search-service", "to": "ai-context-engine", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "entity-engine", "to": "business-records-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "config-group-published-catalog", "to": "structure-metadata-data", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "decision-control-plane-not-tenant", "to": "platform-identity", "type": ArchitectureLinkType.USED_BY.value},
    # --- Interface ↔ Components ---
    {"from": "avatar", "to": "user-menu", "type": ArchitectureLinkType.USES.value},
    {"from": "notification-center", "to": "platform-notification", "type": ArchitectureLinkType.USES.value},
    {"from": "avatar", "to": "user-menu", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "notification-center", "to": "platform-notification", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "top-navigation", "to": "global-search", "type": ArchitectureLinkType.USES.value},
    {"from": "top-navigation", "to": "notification-center", "type": ArchitectureLinkType.USES.value},
    {"from": "top-navigation", "to": "avatar", "type": ArchitectureLinkType.USES.value},
    {"from": "top-navigation", "to": "settings-entry", "type": ArchitectureLinkType.USES.value},
    {"from": "side-navigation", "to": "platform-sidebar", "type": ArchitectureLinkType.USES.value},
    {"from": "side-navigation", "to": "platform-tree", "type": ArchitectureLinkType.USES.value},
    {"from": "breadcrumbs", "to": "platform-breadcrumbs", "type": ArchitectureLinkType.USES.value},
    {"from": "context-menu", "to": "platform-context-menu", "type": ArchitectureLinkType.USES.value},
    {"from": "modal-zone", "to": "platform-modal", "type": ArchitectureLinkType.USES.value},
    {"from": "side-panel", "to": "platform-drawer", "type": ArchitectureLinkType.USES.value},
    {"from": "action-panel", "to": "platform-toolbar", "type": ArchitectureLinkType.USES.value},
    {"from": "entity-card", "to": "platform-card", "type": ArchitectureLinkType.USES.value},
    {"from": "workspace-tabs", "to": "platform-tabs", "type": ArchitectureLinkType.USES.value},
    {"from": "picker-panel", "to": "object-picker", "type": ArchitectureLinkType.USES.value},
    {"from": "picker-panel", "to": "user-picker", "type": ArchitectureLinkType.USES.value},
    {"from": "picker-panel", "to": "file-picker", "type": ArchitectureLinkType.USES.value},
    {"from": "view-surface", "to": "platform-table", "type": ArchitectureLinkType.USES.value},
    {"from": "view-surface", "to": "platform-tree", "type": ArchitectureLinkType.USES.value},
    {"from": "view-surface", "to": "platform-card", "type": ArchitectureLinkType.USES.value},
    {"from": "view-surface", "to": "platform-kanban", "type": ArchitectureLinkType.USES.value},
    {"from": "view-surface", "to": "platform-calendar", "type": ArchitectureLinkType.USES.value},
    {"from": "side-navigation", "to": "platform-sidebar", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "side-navigation", "to": "platform-tree", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "breadcrumbs", "to": "platform-breadcrumbs", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "context-menu", "to": "platform-context-menu", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "modal-zone", "to": "platform-modal", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "side-panel", "to": "platform-drawer", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "action-panel", "to": "platform-toolbar", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "entity-card", "to": "platform-card", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "workspace-tabs", "to": "platform-tabs", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "picker-panel", "to": "object-picker", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "picker-panel", "to": "user-picker", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "picker-panel", "to": "file-picker", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "view-surface", "to": "platform-table", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "view-surface", "to": "platform-tree", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "view-surface", "to": "platform-card", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "view-surface", "to": "platform-kanban", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "view-surface", "to": "platform-calendar", "type": ArchitectureLinkType.USED_BY.value},
    # WI-ARCH-CORE-002: core ↔ data / services / configuration / standards
    {"from": "object-types-engine", "to": "structure-metadata-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "fields-engine", "to": "object-types-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "fields-engine", "to": "structure-metadata-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "relation-engine", "to": "structure-metadata-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "relation-engine", "to": "relation-instances-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "view-engine", "to": "structure-metadata-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "view-engine", "to": "entity-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "action-engine", "to": "structure-metadata-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "action-engine", "to": "entity-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "process-engine", "to": "entity-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "process-engine", "to": "action-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "entity-engine", "to": "permission-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "event-engine", "to": "journals-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "navigation-engine", "to": "config-group-navigation", "type": ArchitectureLinkType.USES.value},
    {"from": "ai-context-engine", "to": "permission-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "constitution-norm-system-entity-standard", "to": "entity-engine", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "constitution-norm-system-entity-standard", "to": "object-types-engine", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "constitution-norm-display-not-id", "to": "fields-engine", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "standard-data-event-journal", "to": "event-engine", "type": ArchitectureLinkType.USED_BY.value},
]
