"""Canonical architecture catalog seed (WI-ARCH-02 synthesis)."""

from __future__ import annotations

from app.modules.platform.architecture_navigator.constants import (
    ArchitectureComponentType,
    ArchitectureLinkType,
    ArchitectureSourceKind,
)

CatalogComponent = dict
CatalogLink = dict

CATALOG_COMPONENTS: list[CatalogComponent] = [
    # --- Контуры ---
    {
        "component_key": "control-plane",
        "technical_name": "Control Plane",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Контур управления платформой",
        "description": "Глобальное управление жизненным циклом платформы, компаниями и релизами.",
        "purpose": "Управление жизненным циклом платформы",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "dev-environment",
        "technical_name": "DEV",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Среда разработки",
        "description": "Рабочая среда проектирования метаданных и платформенных артефактов.",
        "purpose": "Проектирование и отладка структуры платформы",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "template-environment",
        "technical_name": "TEMPLATE",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Эталонная среда",
        "description": "Эталонная публикация структуры для тиражирования в клиентские компании.",
        "purpose": "Канонический шаблон для CLIENT tenant",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "client-environment",
        "technical_name": "CLIENT",
        "component_type": ArchitectureComponentType.CONTOUR.value,
        "category_key": "contours",
        "title": "Клиентские компании",
        "description": "Рабочие tenant компаний с изолированными бизнес-данными.",
        "purpose": "Эксплуатация платформы конечными организациями",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Подсистемы ---
    {
        "component_key": "studio",
        "technical_name": "Studio",
        "component_type": ArchitectureComponentType.SUBSYSTEM.value,
        "category_key": "subsystems",
        "title": "Конструктор платформы",
        "description": "Режим проектирования объектов, страниц, процессов и публикаций.",
        "purpose": "Проектирование метаданных и структуры портала",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "office",
        "technical_name": "Office",
        "component_type": ArchitectureComponentType.SUBSYSTEM.value,
        "category_key": "subsystems",
        "title": "Рабочее пространство",
        "description": "Пользовательский режим работы с данными, задачами и процессами.",
        "purpose": "Операционная работа пользователей tenant",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "tenant-administration",
        "technical_name": "Tenant Administration",
        "component_type": ArchitectureComponentType.SUBSYSTEM.value,
        "category_key": "subsystems",
        "title": "Администрирование компании",
        "description": "Управление пользователями, ролями и настройками конкретного tenant.",
        "purpose": "Администрирование внутри границ компании",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Ядро ---
    {
        "component_key": "entity-engine",
        "technical_name": "Entity Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок объектов",
        "description": "Источник истины бизнес-данных tenant: записи объектов и их версии.",
        "purpose": "Хранение и доступ к данным объектов",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "relation-engine",
        "technical_name": "Relation Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок связей",
        "description": "Связи между записями объектов по опубликованным определениям.",
        "purpose": "Связывание сущностей в графе данных",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "event-engine",
        "technical_name": "Event Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок событий",
        "description": "Журналы событий, аудит и dev-development записи.",
        "purpose": "Фиксация значимых изменений и событий",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "process-engine",
        "technical_name": "Process Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок процессов",
        "description": "Исполнение бизнес-процессов поверх объектов и действий.",
        "purpose": "Оркестрация бизнес-процессов",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "action-engine",
        "technical_name": "Action Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Движок действий",
        "description": "Определения действий, формы и размещения в UI.",
        "purpose": "Пользовательские и системные действия над данными",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "ai-context-engine",
        "technical_name": "AI Context Engine",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Контекстный движок ИИ",
        "description": "Контекст для YASII/ЯСИИ: corpus, ACE, project knowledge.",
        "purpose": "Контекст для встроенного ИИ-сотрудника",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "published-catalog",
        "technical_name": "Published Catalog",
        "component_type": ArchitectureComponentType.CORE_COMPONENT.value,
        "category_key": "core",
        "title": "Каталог опубликованной структуры",
        "description": "Runtime-читаемая структура объектов, полей, связей и представлений.",
        "purpose": "Источник истины метаданных в runtime",
        "parent_key": None,
        "sort_order": 70,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Платформенные компоненты ---
    {
        "component_key": "platform-modal",
        "technical_name": "PlatformModal",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Модальное окно платформы",
        "description": "Стандартное модальное окно с drag, resize и persist bounds (Platform Modal Standard).",
        "purpose": "Единообразные панели настроек и диалоги",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-page",
        "technical_name": "PlatformPage",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Страница платформы",
        "description": "Каркас страницы Studio/Office с контрактом layout и зонами toolbar.",
        "purpose": "Единая структура экранов платформы",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-table",
        "technical_name": "PlatformTable",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Таблица платформы",
        "description": "Табличное представление данных объектов с фильтрами и настройками вида.",
        "purpose": "Отображение и работа со списками записей",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-form",
        "technical_name": "PlatformForm",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Форма платформы",
        "description": "Стандартная форма редактирования полей объекта и действий.",
        "purpose": "Ввод и редактирование данных",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-tree",
        "technical_name": "PlatformTree",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Дерево платформы",
        "description": "Иерархическое дерево навигации и структуры (sidebar, object tree).",
        "purpose": "Навигация по иерархии",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-card",
        "technical_name": "PlatformCard",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Карточка платформы",
        "description": "Контейнер детальной информации с секциями и полями.",
        "purpose": "Просмотр и редактирование сущности",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-tabs",
        "technical_name": "PlatformTabs",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Вкладки платформы",
        "description": "Переключение представлений и рабочих зон внутри страницы.",
        "purpose": "Организация контента по вкладкам",
        "parent_key": None,
        "sort_order": 70,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-drawer",
        "technical_name": "PlatformDrawer",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Выдвижная панель",
        "description": "Боковая панель для контекстных действий и деталей.",
        "purpose": "Контекстные панели без смены страницы",
        "parent_key": None,
        "sort_order": 80,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-toolbar",
        "technical_name": "PlatformToolbar",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Панель инструментов",
        "description": "Зона действий страницы: кнопки, фильтры, контекстные команды.",
        "purpose": "Действия и инструменты на уровне экрана",
        "parent_key": None,
        "sort_order": 90,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-notification",
        "technical_name": "PlatformNotification",
        "component_type": ArchitectureComponentType.PLATFORM_COMPONENT.value,
        "category_key": "platform_components",
        "title": "Уведомление платформы",
        "description": "Компонент отображения уведомлений и toast-сообщений.",
        "purpose": "Обратная связь и оповещения пользователю",
        "parent_key": None,
        "sort_order": 100,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Платформенные элементы интерфейса ---
    {
        "component_key": "avatar",
        "technical_name": "Avatar",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Аватар пользователя",
        "description": "Отображение фото/инициалов пользователя в оболочке платформы.",
        "purpose": "Визуальная идентификация пользователя",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "user-menu",
        "technical_name": "User Menu",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Меню пользователя",
        "description": "Выпадающее меню профиля, выхода и персональных действий.",
        "purpose": "Доступ к профилю и сессии",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "settings-button",
        "technical_name": "Settings Button",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Кнопка настроек",
        "description": "Точка входа в настройки страницы, вида или рабочей области.",
        "purpose": "Быстрый доступ к настройкам контекста",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "notification-bell",
        "technical_name": "Notification Bell",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Колокол уведомлений",
        "description": "Индикатор и список непрочитанных уведомлений в header.",
        "purpose": "Доступ к уведомлениям платформы",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "global-search",
        "technical_name": "Global Search",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Глобальный поиск",
        "description": "Единый поиск по runtime и designer из header платформы.",
        "purpose": "Быстрый поиск сущностей и страниц",
        "parent_key": None,
        "sort_order": 50,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "top-navigation",
        "technical_name": "Top Navigation",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Верхняя панель",
        "description": "App header: бренд, поиск, уведомления, профиль.",
        "purpose": "Глобальная навигация и действия",
        "parent_key": None,
        "sort_order": 60,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "side-navigation",
        "technical_name": "Side Navigation",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Боковое меню",
        "description": "Sidebar с деревом разделов Studio/Office.",
        "purpose": "Основная навигация по разделам tenant",
        "parent_key": None,
        "sort_order": 70,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "breadcrumbs",
        "technical_name": "Breadcrumbs",
        "component_type": ArchitectureComponentType.PLATFORM_UI_ELEMENT.value,
        "category_key": "platform_ui_elements",
        "title": "Хлебные крошки",
        "description": "Цепочка навигации текущего контекста страницы.",
        "purpose": "Ориентация в иерархии разделов",
        "parent_key": None,
        "sort_order": 80,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Модули (выборочно) ---
    {
        "component_key": "calendar-module",
        "technical_name": "Calendar Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "Календарь",
        "description": "Модуль событий календаря tenant.",
        "purpose": "Планирование и отображение событий",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "chats-module",
        "technical_name": "Chats Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "Чаты",
        "description": "Коммуникации внутри tenant.",
        "purpose": "Обмен сообщениями между пользователями",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "document-libraries-module",
        "technical_name": "Document Libraries Module",
        "component_type": ArchitectureComponentType.MODULE.value,
        "category_key": "modules",
        "title": "Библиотеки документов",
        "description": "Хранение и просмотр документов с OnlyOffice.",
        "purpose": "Документооборот tenant",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Службы ---
    {
        "component_key": "session-bridge",
        "technical_name": "Session Bridge",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Мост сессий",
        "description": "Связь platform identity и tenant runtime без смешения контуров.",
        "purpose": "Безопасная авторизация между контурами",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "platform-identity",
        "technical_name": "Platform Identity",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Идентичность платформы",
        "description": "Глобальные пользователи платформы и platform users.",
        "purpose": "Идентификация на уровне платформы",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "release-governance",
        "technical_name": "Release Governance",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Управление релизами",
        "description": "Pipeline релизов, пакетов, деплойментов и откатов.",
        "purpose": "Контролируемая доставка версий платформы",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "publication-pipeline",
        "technical_name": "Publication Pipeline",
        "component_type": ArchitectureComponentType.SERVICE.value,
        "category_key": "services",
        "title": "Конвейер публикаций",
        "description": "Публикация метаданных DEV → TEMPLATE → CLIENT.",
        "purpose": "Тиражирование структуры между средами",
        "parent_key": None,
        "sort_order": 40,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Данные ---
    {
        "component_key": "platform-audit-journal-data",
        "technical_name": "Platform Audit Journal",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Журнал аудита платформы",
        "description": "Записи platform-scope audit journal.",
        "purpose": "Аудит действий на уровне платформы",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "runtime-entities-data",
        "technical_name": "Runtime Entities",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Записи объектов runtime",
        "description": "Таблицы runtime_entity_records и связанные артефакты.",
        "purpose": "Бизнес-данные tenant",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "designer-metadata-data",
        "technical_name": "Designer Metadata",
        "component_type": ArchitectureComponentType.DATA_TYPE.value,
        "category_key": "data",
        "title": "Метаданные конструктора",
        "description": "Черновики object types, fields, views в designer.",
        "purpose": "Проектируемая структура до публикации",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Решения ---
    {
        "component_key": "decision-control-plane-not-tenant",
        "technical_name": "Control Plane ≠ Tenant",
        "component_type": ArchitectureComponentType.ARCHITECTURE_DECISION.value,
        "category_key": "decisions",
        "title": "Control Plane ≠ Tenant",
        "description": "Контур управления платформой не является tenant-компанией.",
        "purpose": "Разделение глобального и tenant-контекста",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "decision-platform-owner-not-tenant-user",
        "technical_name": "Platform Owner ≠ Tenant User",
        "component_type": ArchitectureComponentType.ARCHITECTURE_DECISION.value,
        "category_key": "decisions",
        "title": "Platform Owner ≠ Tenant User",
        "description": "Владелец платформы и пользователь компании — разные роли.",
        "purpose": "Разграничение полномочий владельца и tenant",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "decision-entity-sot",
        "technical_name": "Entity as Source of Truth",
        "component_type": ArchitectureComponentType.ARCHITECTURE_DECISION.value,
        "category_key": "decisions",
        "title": "Entity — источник истины данных",
        "description": "Бизнес-данные хранятся в Entity Engine, не в UI.",
        "purpose": "Единый SoT для данных tenant",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    # --- Запреты ---
    {
        "component_key": "restriction-no-tenant-data-in-control-plane",
        "technical_name": "No Tenant Business Data in Control Plane",
        "component_type": ArchitectureComponentType.ARCHITECTURE_RESTRICTION.value,
        "category_key": "restrictions",
        "title": "Не хранить бизнес-данные компаний в Control Plane",
        "description": "Control Plane управляет платформой, не хранит клиентские записи.",
        "purpose": "Изоляция контуров",
        "parent_key": None,
        "sort_order": 10,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "restriction-no-display-as-id",
        "technical_name": "No Display Fields as Identifiers",
        "component_type": ArchitectureComponentType.ARCHITECTURE_RESTRICTION.value,
        "category_key": "restrictions",
        "title": "Не использовать title/name как идентификатор",
        "description": "Идентификация только через id, key, code и стабильные технические поля.",
        "purpose": "Стабильность ссылок и защиты",
        "parent_key": None,
        "sort_order": 20,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
    {
        "component_key": "restriction-runtime-no-designer-draft",
        "technical_name": "Runtime Must Not Read Designer Draft",
        "component_type": ArchitectureComponentType.ARCHITECTURE_RESTRICTION.value,
        "category_key": "restrictions",
        "title": "Runtime не читает черновик designer",
        "description": "Runtime использует только Published Catalog.",
        "purpose": "Разделение проектирования и эксплуатации",
        "parent_key": None,
        "sort_order": 30,
        "catalog_sources": [ArchitectureSourceKind.CATALOG_SEED.value],
    },
]

CATALOG_LINKS: list[CatalogLink] = [
    {"from": "control-plane", "to": "session-bridge", "type": ArchitectureLinkType.USES.value},
    {"from": "control-plane", "to": "platform-identity", "type": ArchitectureLinkType.USES.value},
    {"from": "control-plane", "to": "release-governance", "type": ArchitectureLinkType.USES.value},
    {"from": "control-plane", "to": "platform-audit-journal-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "dev-environment", "to": "studio", "type": ArchitectureLinkType.USES.value},
    {"from": "dev-environment", "to": "designer-metadata-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "template-environment", "to": "published-catalog", "type": ArchitectureLinkType.USES.value},
    {"from": "client-environment", "to": "office", "type": ArchitectureLinkType.USES.value},
    {"from": "client-environment", "to": "runtime-entities-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "studio", "to": "published-catalog", "type": ArchitectureLinkType.USES.value},
    {"from": "studio", "to": "publication-pipeline", "type": ArchitectureLinkType.USES.value},
    {"from": "office", "to": "entity-engine", "type": ArchitectureLinkType.USES.value},
    {"from": "office", "to": "published-catalog", "type": ArchitectureLinkType.USES.value},
    {"from": "entity-engine", "to": "runtime-entities-data", "type": ArchitectureLinkType.STORES_DATA.value},
    {"from": "published-catalog", "to": "designer-metadata-data", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "control-plane", "to": "dev-environment", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "control-plane", "to": "template-environment", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "control-plane", "to": "client-environment", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "session-bridge", "to": "studio", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "session-bridge", "to": "office", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "decision-control-plane-not-tenant", "to": "control-plane", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "restriction-no-display-as-id", "to": "entity-engine", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "studio", "to": "platform-page", "type": ArchitectureLinkType.USES.value},
    {"from": "studio", "to": "platform-modal", "type": ArchitectureLinkType.USES.value},
    {"from": "office", "to": "platform-page", "type": ArchitectureLinkType.USES.value},
    {"from": "office", "to": "platform-table", "type": ArchitectureLinkType.USES.value},
    {"from": "avatar", "to": "user-menu", "type": ArchitectureLinkType.USES.value},
    {"from": "notification-bell", "to": "platform-notification", "type": ArchitectureLinkType.USES.value},
    {"from": "studio", "to": "platform-page", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "studio", "to": "platform-modal", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "office", "to": "platform-page", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "office", "to": "platform-table", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "avatar", "to": "user-menu", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "notification-bell", "to": "platform-notification", "type": ArchitectureLinkType.USED_BY.value},
    {"from": "top-navigation", "to": "global-search", "type": ArchitectureLinkType.USES.value},
    {"from": "top-navigation", "to": "notification-bell", "type": ArchitectureLinkType.USES.value},
    {"from": "top-navigation", "to": "avatar", "type": ArchitectureLinkType.USES.value},
    {"from": "side-navigation", "to": "platform-tree", "type": ArchitectureLinkType.USES.value},
]
