COMMENT_KIND_USER = "user"
COMMENT_KIND_SYSTEM = "system"

COMMENT_BODY_FORMAT_PLAIN = "plain"
COMMENT_BODY_FORMAT_MARKDOWN = "markdown_lite"

COMMENT_SYSTEM_EVENT_STATUS_CHANGED = "status_changed"
COMMENT_SYSTEM_EVENT_DUE_DATE_CHANGED = "due_date_changed"
COMMENT_SYSTEM_EVENT_ASSIGNEE_CHANGED = "assignee_changed"
COMMENT_SYSTEM_EVENT_PRIORITY_CHANGED = "priority_changed"
COMMENT_SYSTEM_EVENT_FILE_ADDED = "file_added"

COMMENT_REACTION_LIKE = "like"
COMMENT_REACTION_DISLIKE = "dislike"
COMMENT_REACTION_HEART = "heart"
COMMENT_REACTION_FIRE = "fire"
COMMENT_REACTION_PARTY = "party"
COMMENT_REACTION_CLAP = "clap"
COMMENT_REACTION_WARNING = "warning"

ALLOWED_COMMENT_REACTIONS = {
    COMMENT_REACTION_LIKE,
    COMMENT_REACTION_DISLIKE,
    COMMENT_REACTION_HEART,
    COMMENT_REACTION_FIRE,
    COMMENT_REACTION_PARTY,
    COMMENT_REACTION_CLAP,
    COMMENT_REACTION_WARNING,
}