"""Tenant membership lifecycle constants."""

MEMBERSHIP_STATUS_INVITED = "invited"
MEMBERSHIP_STATUS_ACTIVE = "active"
MEMBERSHIP_STATUS_SUSPENDED = "suspended"
MEMBERSHIP_STATUS_DISMISSED = "dismissed"

ACTIVE_MEMBERSHIP_STATUSES = frozenset(
    {MEMBERSHIP_STATUS_INVITED, MEMBERSHIP_STATUS_ACTIVE}
)

LOOKUP_OUTCOME_NOT_FOUND = "not_found"
LOOKUP_OUTCOME_NEW = "new"
LOOKUP_OUTCOME_FOUND_EXISTING = "found_existing"
LOOKUP_OUTCOME_ALREADY_MEMBER = "already_member"
LOOKUP_OUTCOME_DISMISSED = "dismissed"
