export const calendarStyles = {
  page: {
    width: "100%",
    height: "100%",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    background: "#FAFAFA",
    overflow: "hidden",
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "10px 16px",
    borderBottom: "1px solid #EDEBE9",
    background: "#FFFFFF",
    minHeight: 52,
    boxSizing: "border-box",
  },
  toolbarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  navGroup: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    marginLeft: 4,
  },
  periodTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: "#201F1E",
    marginLeft: 8,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  viewSwitcher: {
    display: "inline-flex",
    alignItems: "center",
    border: "1px solid #C8C6C4",
    borderRadius: 4,
    overflow: "hidden",
    flexShrink: 0,
  },
  viewButton: {
    height: 32,
    border: "none",
    borderRight: "1px solid #C8C6C4",
    background: "#FFFFFF",
    color: "#201F1E",
    fontSize: 13,
    fontWeight: 500,
    padding: "0 14px",
    cursor: "pointer",
  },
  viewButtonActive: {
    height: 32,
    border: "none",
    borderRight: "1px solid #C8C6C4",
    background: "#EFF6FC",
    color: "#0078D4",
    fontSize: 13,
    fontWeight: 600,
    padding: "0 14px",
    cursor: "pointer",
  },
  body: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "240px minmax(0, 1fr) 300px",
    overflow: "hidden",
  },
  sidebar: {
    borderRight: "1px solid #EDEBE9",
    background: "#FFFFFF",
    minHeight: 0,
    overflow: "auto",
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  sidebarSection: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  sidebarSectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "#605E5C",
    padding: "0 4px",
  },
  sidebarList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  sidebarListItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#201F1E",
    padding: "4px 6px",
    borderRadius: 4,
    cursor: "default",
  },
  sidebarCheckbox: {
    margin: 0,
  },
  sidebarColorDot: {
    width: 10,
    height: 10,
    borderRadius: 2,
    flexShrink: 0,
  },
  sidebarListLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebarFilters: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "0 4px",
  },
  sidebarFilterInput: {
    width: "100%",
    height: 30,
    border: "1px solid #C8C6C4",
    borderRadius: 4,
    padding: "0 8px",
    fontSize: 12,
    boxSizing: "border-box",
    background: "#FFFFFF",
  },
  filterChipGroup: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
  },
  filterChip: {
    border: "1px solid #C8C6C4",
    background: "#FFFFFF",
    color: "#201F1E",
    borderRadius: 999,
    fontSize: 11,
    padding: "4px 8px",
    cursor: "pointer",
  },
  filterChipActive: {
    border: "1px solid #0078D4",
    background: "#EFF6FC",
    color: "#0078D4",
    borderRadius: 999,
    fontSize: 11,
    padding: "4px 8px",
    cursor: "pointer",
    fontWeight: 600,
  },
  miniMonth: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  miniMonthHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  miniMonthTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "#201F1E",
    textTransform: "capitalize",
    flex: 1,
    textAlign: "center",
  },
  miniMonthGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 2,
  },
  miniMonthWeekday: {
    fontSize: 11,
    fontWeight: 600,
    color: "#605E5C",
    textAlign: "center",
    padding: "2px 0",
  },
  miniMonthDay: {
    border: "none",
    background: "transparent",
    color: "#201F1E",
    fontSize: 12,
    borderRadius: 999,
    width: 28,
    height: 28,
    margin: "0 auto",
    cursor: "pointer",
    padding: 0,
  },
  miniMonthDayMuted: {
    color: "#A19F9D",
  },
  miniMonthDayToday: {
    border: "1px solid #0078D4",
  },
  miniMonthDaySelected: {
    background: "#0078D4",
    color: "#FFFFFF",
  },
  mainPanel: {
    minHeight: 0,
    overflow: "auto",
    padding: 12,
    background: "#FAFAFA",
  },
  mainPanelTimeGrid: {
    minHeight: 0,
    overflow: "hidden",
    padding: 12,
    background: "#FAFAFA",
    display: "flex",
    flexDirection: "column",
  },
  detailsPanel: {
    borderLeft: "1px solid #EDEBE9",
    background: "#FFFFFF",
    minHeight: 0,
    overflow: "auto",
    padding: 16,
  },
  monthView: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    minHeight: "100%",
  },
  monthWeekdayRow: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    borderBottom: "1px solid #EDEBE9",
    background: "#FFFFFF",
  },
  monthWeekdayHeader: {
    fontSize: 12,
    fontWeight: 600,
    color: "#605E5C",
    padding: "8px 6px",
    textAlign: "center",
  },
  monthGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    flex: 1,
    minHeight: 520,
  },
  monthCell: {
    minHeight: 96,
    borderRight: "1px solid #EDEBE9",
    borderBottom: "1px solid #EDEBE9",
    background: "#FFFFFF",
    padding: "6px 4px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    boxSizing: "border-box",
  },
  monthCellMuted: {
    background: "#FAFAFA",
  },
  monthCellToday: {
    background: "#F3F9FD",
  },
  monthDayLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "#605E5C",
    width: 24,
    height: 24,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
  },
  monthDayLabelToday: {
    background: "#0078D4",
    color: "#FFFFFF",
  },
  monthEventList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minHeight: 0,
  },
  monthMoreLabel: {
    fontSize: 11,
    color: "#605E5C",
    paddingLeft: 4,
  },
  timeGridWrapper: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    height: "100%",
    background: "#FFFFFF",
    border: "1px solid #EDEBE9",
    borderRadius: 4,
    overflow: "hidden",
  },
  timeGridScroll: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    scrollbarGutter: "stable",
  },
  timeGridHeader: {
    display: "grid",
    gridTemplateColumns: "56px repeat(7, minmax(0, 1fr))",
    borderBottom: "1px solid #EDEBE9",
    background: "#FFFFFF",
    position: "sticky",
    top: 0,
    zIndex: 3,
    flexShrink: 0,
  },
  timeGridHeaderDay: {
    display: "grid",
    gridTemplateColumns: "56px minmax(0, 1fr)",
    borderBottom: "1px solid #EDEBE9",
    background: "#FFFFFF",
    position: "sticky",
    top: 0,
    zIndex: 3,
    flexShrink: 0,
  },
  timeGridCorner: {
    borderRight: "1px solid #EDEBE9",
  },
  timeGridDayHeader: {
    padding: "8px 6px",
    textAlign: "center",
    borderRight: "1px solid #EDEBE9",
  },
  timeGridDayHeaderToday: {
    background: "#EFF6FC",
  },
  timeGridDayName: {
    fontSize: 11,
    color: "#605E5C",
    textTransform: "capitalize",
  },
  timeGridDayNumber: {
    fontSize: 18,
    fontWeight: 600,
    color: "#201F1E",
  },
  timeGridBody: {
    display: "grid",
    gridTemplateColumns: "56px minmax(0, 1fr)",
    minHeight: 0,
  },
  timeAxis: {
    borderRight: "1px solid #EDEBE9",
    background: "#FFFFFF",
  },
  timeAxisHour: {
    fontSize: 11,
    color: "#605E5C",
    padding: "0 6px",
    boxSizing: "border-box",
    borderBottom: "1px solid #F3F2F1",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-end",
  },
  timeGridColumns: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    minWidth: 0,
  },
  timeGridColumnsDay: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    minWidth: 0,
  },
  timeGridColumn: {
    position: "relative",
    borderRight: "1px solid #EDEBE9",
    background: "#FFFFFF",
  },
  timeGridColumnToday: {
    background: "#FCFDFF",
  },
  timeGridHourCell: {
    borderBottom: "1px solid #F3F2F1",
    boxSizing: "border-box",
  },
  timeGridEventsLayer: {
    position: "absolute",
    inset: 0,
    zIndex: 1,
  },
  emptyState: {
    padding: 24,
    textAlign: "center",
    color: "#605E5C",
    fontSize: 14,
  },
  primaryButton: {
    height: 32,
    border: "none",
    borderRadius: 4,
    background: "#0078D4",
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: 600,
    padding: "0 14px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  secondaryButton: {
    height: 32,
    border: "1px solid #C8C6C4",
    borderRadius: 4,
    background: "#FFFFFF",
    color: "#201F1E",
    fontSize: 13,
    fontWeight: 500,
    padding: "0 12px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  iconButton: {
    width: 32,
    height: 32,
    border: "1px solid #C8C6C4",
    borderRadius: 4,
    background: "#FFFFFF",
    color: "#201F1E",
    fontSize: 18,
    lineHeight: 1,
    cursor: "pointer",
    padding: 0,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    background: "#FFFFFF",
    border: "1px solid #EDEBE9",
    borderRadius: 4,
    overflow: "hidden",
  },
  th: {
    textAlign: "left",
    fontSize: 12,
    fontWeight: 600,
    color: "#605E5C",
    padding: "10px 12px",
    borderBottom: "1px solid #EDEBE9",
    background: "#FAFAFA",
  },
  td: {
    fontSize: 13,
    color: "#201F1E",
    padding: "12px",
    borderBottom: "1px solid #F3F2F1",
    verticalAlign: "top",
  },
  rowActive: {
    background: "#EFF6FC",
  },
  monthDayLabelLegacy: {
    fontSize: 12,
    fontWeight: 700,
    color: "#334155",
  },
  monthEventChip: {
    fontSize: 11,
    lineHeight: 1.3,
    padding: "2px 6px",
    borderRadius: 2,
    background: "#DEECF9",
    color: "#0078D4",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  toolbarTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#0F172A",
    marginRight: "auto",
  },
  toolbarGroup: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  filterInput: {
    minWidth: 160,
    height: 34,
    border: "1px solid #CBD5E1",
    borderRadius: 8,
    padding: "0 10px",
    fontSize: 13,
    background: "#FFFFFF",
  },
  tabButtonActive: {
    height: 34,
    border: "1px solid #2563EB",
    borderRadius: 8,
    background: "#EFF6FF",
    color: "#1D4ED8",
    fontSize: 13,
    fontWeight: 600,
    padding: "0 12px",
    cursor: "pointer",
  },
  tabButton: {
    height: 34,
    border: "1px solid #CBD5E1",
    borderRadius: 8,
    background: "#FFFFFF",
    color: "#334155",
    fontSize: 13,
    fontWeight: 500,
    padding: "0 12px",
    cursor: "pointer",
  },
  contextMenu: {
    position: "fixed",
    zIndex: 10050,
    minWidth: 220,
    padding: 4,
    borderRadius: 6,
    border: "1px solid #EDEBE9",
    background: "#FFFFFF",
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.14)",
    boxSizing: "border-box",
  },
  contextMenuItem: {
    display: "block",
    width: "100%",
    border: "none",
    background: "transparent",
    color: "#201F1E",
    fontSize: 13,
    lineHeight: 1.3,
    textAlign: "left",
    padding: "8px 12px",
    borderRadius: 4,
    cursor: "pointer",
  },
  contextMenuItemDanger: {
    color: "#A4262C",
  },
};
