export const companiesWorkspaceStyles = {
  tabContent: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    overflow: "hidden",
  },
  tabToolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
    paddingTop: 4,
  },
  workspace: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(620px, 1fr) minmax(430px, 500px)",
    gap: 18,
    alignItems: "stretch",
    overflow: "hidden",
  },
  listPanel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    overflow: "hidden",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.05)",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  toolbar: {
    padding: 12,
    borderBottom: "1px solid #e2e8f0",
    flexShrink: 0,
  },
  searchInput: {
    width: "100%",
    height: 44,
    border: "1px solid #cbd5e1",
    borderRadius: 12,
    padding: "0 14px",
    fontSize: 14,
    boxSizing: "border-box",
    outline: "none",
    background: "#ffffff",
  },
  tableHeader: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 1.35fr) 120px 90px 110px",
    gap: 10,
    alignItems: "center",
    padding: "10px 16px",
    fontSize: 12,
    fontWeight: 700,
    color: "#64748b",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
    flexShrink: 0,
  },
  listBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
  listRow: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 1.35fr) 120px 90px 110px",
    gap: 10,
    alignItems: "center",
    width: "100%",
    minHeight: 64,
    padding: "12px 16px",
    border: "none",
    borderBottom: "1px solid #f1f5f9",
    background: "#ffffff",
    cursor: "pointer",
    textAlign: "left",
    outline: "none",
    boxSizing: "border-box",
    transition: "background 140ms ease",
  },
  listRowSelected: {
    background: "#eff6ff",
  },
  companyName: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0f172a",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listCellMuted: {
    color: "#64748b",
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  mutedText: {
    fontSize: 13,
    color: "#64748b",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  emptyState: {
    padding: 24,
    color: "#64748b",
    fontSize: 14,
  },
  detailPanel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.05)",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  detailHeader: {
    padding: "16px 18px 12px",
    borderBottom: "1px solid #e2e8f0",
    flexShrink: 0,
  },
  detailTitle: {
    margin: 0,
    fontSize: 17,
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1.3,
  },
  detailBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "14px 18px 18px",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "132px 1fr",
    gap: "10px 14px",
    fontSize: 14,
    marginBottom: 16,
  },
  detailLabel: {
    color: "#64748b",
    fontWeight: 600,
    fontSize: 12,
  },
  detailValue: {
    color: "#0f172a",
    lineHeight: 1.45,
  },
  superadminSection: {
    marginBottom: 16,
    paddingTop: 4,
    borderTop: "1px solid #f1f5f9",
  },
  superadminTitle: {
    margin: "0 0 12px",
    fontSize: 15,
    fontWeight: 700,
    color: "#0f172a",
  },
  superadminEmpty: {
    margin: "0 0 12px",
    color: "#64748b",
    fontSize: 14,
  },
  superadminActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  actionsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 12,
    borderTop: "1px solid #f1f5f9",
  },
  primaryButton: {
    border: "none",
    borderRadius: 10,
    padding: "9px 14px",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "9px 14px",
    background: "#fff",
    color: "#0f172a",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
  dangerButton: {
    border: "none",
    borderRadius: 10,
    padding: "9px 14px",
    background: "#dc2626",
    color: "#fff",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
  disabledButton: {
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    padding: "9px 14px",
    background: "#f8fafc",
    color: "#94a3b8",
    fontWeight: 600,
    fontSize: 13,
    cursor: "not-allowed",
  },
  error: {
    color: "#b91c1c",
    fontSize: 14,
  },
  placeholderCard: {
    padding: 24,
    color: "#64748b",
    fontSize: 14,
    lineHeight: 1.5,
  },
  kicker: {
    fontSize: 13,
    fontWeight: 700,
    color: "#7c3aed",
    marginBottom: 4,
  },
  title: {
    margin: 0,
    fontSize: 20,
    fontWeight: 800,
    color: "#0f172a",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 14,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "#334155",
  },
  input: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
  },
  textarea: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    minHeight: 96,
    resize: "vertical",
  },
};
