"""YASII demo/runtime pipeline trace stage identifiers."""

MEMORY_LOADED = "memory_loaded"
MEMORY_SAVED = "memory_saved"
MEMORY_DELETED = "memory_deleted"
TENANT_MEMORY_LOADED = "tenant_memory_loaded"
TENANT_MEMORY_SAVED = "tenant_memory_saved"
TENANT_MEMORY_DELETED = "tenant_memory_deleted"
SESSION_MEMORY_LOADED = "session_memory_loaded"
SESSION_MEMORY_UPDATED = "session_memory_updated"
SESSION_MEMORY_CLEARED = "session_memory_cleared"
SESSION_SUMMARY_GENERATED = "session_summary_generated"
DECISION_SAVED = "decision_saved"
DECISION_LOADED = "decision_loaded"
DECISION_UPDATED = "decision_updated"
DECISION_CONFLICT_DETECTED = "decision_conflict_detected"
PROCESS_MEMORY_LOADED = "process_memory_loaded"
PROCESS_MEMORY_SAVED = "process_memory_saved"
PROCESS_MEMORY_LINKED = "process_memory_linked"
PROCESS_MEMORY_INSTANCE_CREATED = "process_memory_instance_created"
PROCESS_MEMORY_STEP_UPDATED = "process_memory_step_updated"
MEMORY_GRAPH_LOADED = "memory_graph_loaded"
MEMORY_GRAPH_LINK_CREATED = "memory_graph_link_created"
MEMORY_GRAPH_SNAPSHOT_GENERATED = "memory_graph_snapshot_generated"
USER_IDENTITY_LOADED = "user_identity_loaded"
USER_IDENTITY_ANSWERED = "user_identity_answered"
STRATEGY_ASSESSMENT_CREATED = "strategy_assessment_created"
STRATEGY_RECOMMENDATION_GENERATED = "strategy_recommendation_generated"
STRATEGY_CONFLICT_DETECTED = "strategy_conflict_detected"
STRATEGY_GOAL_ALIGNMENT_CHECKED = "strategy_goal_alignment_checked"
UNLOCK_SCORE_GENERATED = "unlock_score_generated"
UNLOCK_RANKING_CREATED = "unlock_ranking_created"
UNLOCK_CANDIDATE_SCORED = "unlock_candidate_scored"
BLOCKER_DETECTED = "blocker_detected"
BLOCKER_ASSESSMENT_CREATED = "blocker_assessment_created"
BLOCKER_DEPENDENCY_FOUND = "blocker_dependency_found"
BLOCKER_CONFLICT_FOUND = "blocker_conflict_found"
RECOMMENDATION_GENERATED = "recommendation_generated"
RECOMMENDATION_TEMPLATE_SELECTED = "recommendation_template_selected"
RECOMMENDATION_NEXT_STEP_CREATED = "recommendation_next_step_created"
RECOMMENDATION_BLOCKER_RESOLUTION_CREATED = "recommendation_blocker_resolution_created"
ARCHITECT_PROFILE_LOADED = "architect_profile_loaded"
ARCHITECT_QUESTION_ANSWERED = "architect_question_answered"
ARCHITECT_DEPENDENCY_ANALYZED = "architect_dependency_analyzed"
ARCHITECT_CHANGE_IMPACT_ANALYZED = "architect_change_impact_analyzed"
IMPROVEMENT_QUERY_EXECUTED = "improvement_query_executed"
IMPROVEMENT_CANDIDATE_FOUND = "improvement_candidate_found"
IMPROVEMENT_ASSESSMENT_CREATED = "improvement_assessment_created"
IMPROVEMENT_RECOMMENDATION_GENERATED = "improvement_recommendation_generated"
GOVERNANCE_STATE_LOADED = "governance_state_loaded"
DEVELOPMENT_STATE_LOADED = "development_state_loaded"
DEVELOPMENT_QUALITY_ANALYZED = "development_quality_analyzed"
DEVELOPMENT_DEBT_ANALYZED = "development_debt_analyzed"
DEVELOPMENT_RISK_DETECTED = "development_risk_detected"
DEVELOPMENT_INTELLIGENCE_CREATED = "development_intelligence_created"
BUSINESS_EXPLANATION_CREATED = "business_explanation_created"
BUSINESS_IMPACT_GENERATED = "business_impact_generated"
BUSINESS_VIEW_SELECTED = "business_view_selected"
PROJECT_STATE_LOADED = "project_state_loaded"
PROJECT_AWARENESS_CREATED = "project_awareness_created"
PROJECT_PRIORITY_GENERATED = "project_priority_generated"
PROJECT_BLOCKERS_DETECTED = "project_blockers_detected"
KNOWLEDGE_CORPUS_LOADED = "knowledge_corpus_loaded"
KNOWLEDGE_DOCUMENT_FOUND = "knowledge_document_found"
KNOWLEDGE_SECTION_FOUND = "knowledge_section_found"
KNOWLEDGE_ANSWER_GENERATED = "knowledge_answer_generated"
YASII_E2E_MVP_STARTED = "yasii_e2e_mvp_started"
YASII_E2E_MVP_COMPLETED = "yasii_e2e_mvp_completed"
YASII_E2E_FLOW_VALIDATED = "yasii_e2e_flow_validated"
INTENT_RESOLVED = "intent_resolved"
KNOWLEDGE_RESOLVED = "knowledge_resolved"
GRAPH_RESOLVED = "graph_resolved"
EVIDENCE_RESOLVED = "evidence_resolved"
RULES_EVALUATED = "rules_evaluated"
VERDICT_EVALUATED = "verdict_evaluated"
RESPONSE_BUILT = "response_built"
AUDIT_RECORDED = "audit_recorded"

DEMO_PIPELINE_TRACE: tuple[str, ...] = (
    INTENT_RESOLVED,
    KNOWLEDGE_RESOLVED,
    GRAPH_RESOLVED,
    EVIDENCE_RESOLVED,
    RULES_EVALUATED,
    VERDICT_EVALUATED,
    RESPONSE_BUILT,
    AUDIT_RECORDED,
)
