export const adminTenantsStyles = {
  page: {
    flex: 1,
    minHeight: 0,
    height: "100%",
    padding: "8px 12px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    boxSizing: "border-box",
    background: "#F8FAFC",
    overflowY: "auto",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  },
  kicker: {
    fontSize: 13,
    fontWeight: 700,
    color: "#2563eb",
    marginBottom: 6,
  },
  title: {
    margin: 0,
    fontSize: 24,
    color: "#0f172a",
  },
  subtitle: {
    margin: "8px 0 0",
    fontSize: 14,
    color: "#64748b",
    maxWidth: 720,
  },
  primaryButton: {
    border: "none",
    borderRadius: 10,
    padding: "10px 16px",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
  },
  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 16px",
    background: "#fff",
    color: "#0f172a",
    fontWeight: 600,
    cursor: "pointer",
  },
  card: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 20,
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.04)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 14,
  },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    borderBottom: "1px solid #e2e8f0",
    color: "#475569",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid #f1f5f9",
    color: "#0f172a",
    verticalAlign: "top",
  },
  badgeActive: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 999,
    background: "#dcfce7",
    color: "#166534",
    fontSize: 12,
    fontWeight: 600,
  },
  badgeInactive: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 999,
    background: "#fee2e2",
    color: "#991b1b",
    fontSize: 12,
    fontWeight: 600,
  },
  linkButton: {
    border: "none",
    background: "transparent",
    color: "#2563eb",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
  },
  dangerLinkButton: {
    border: "none",
    background: "transparent",
    color: "#dc2626",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
  },
  dangerButton: {
    border: "none",
    borderRadius: 10,
    padding: "10px 16px",
    background: "#dc2626",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
  },
  error: {
    color: "#b91c1c",
    fontSize: 14,
    marginTop: 8,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 14,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "#334155",
  },
  input: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
  },
  textarea: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    minHeight: 96,
    resize: "vertical",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "180px 1fr",
    gap: "10px 16px",
    fontSize: 14,
  },
  detailLabel: {
    color: "#64748b",
    fontWeight: 600,
  },
  detailValue: {
    color: "#0f172a",
  },
};
