export const EMBEDDED_SURFACE_IDS = {
  DASHBOARD: "dashboard",
  OBJECT_CARD: "object_card",
  REGISTRY: "registry",
  DESIGNER: "designer",
  DOCUMENT: "document",
  PROCESS: "process",
  GLOBAL: "global",
};

export const EMBEDDED_SURFACE_CATALOG = [
  EMBEDDED_SURFACE_IDS.DASHBOARD,
  EMBEDDED_SURFACE_IDS.OBJECT_CARD,
  EMBEDDED_SURFACE_IDS.REGISTRY,
  EMBEDDED_SURFACE_IDS.DESIGNER,
  EMBEDDED_SURFACE_IDS.DOCUMENT,
  EMBEDDED_SURFACE_IDS.PROCESS,
  EMBEDDED_SURFACE_IDS.GLOBAL,
];
