export const platformEnvironmentsStyles = {
  tabContent: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    overflow: "hidden",
  },
  workspace: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(320px, 420px) minmax(430px, 1fr)",
    gap: 18,
    alignItems: "stretch",
    overflow: "hidden",
  },
  listPanel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    overflow: "hidden",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.05)",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  listHeader: {
    padding: "14px 16px",
    borderBottom: "1px solid #e2e8f0",
    fontSize: 13,
    fontWeight: 700,
    color: "#334155",
    background: "#f8fafc",
    flexShrink: 0,
  },
  listBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
  listRow: {
    display: "grid",
    gridTemplateColumns: "56px 1fr",
    gap: 12,
    alignItems: "center",
    width: "100%",
    padding: "14px 16px",
    border: "none",
    borderBottom: "1px solid #eef2f7",
    background: "#ffffff",
    textAlign: "left",
    cursor: "pointer",
  },
  listRowSelected: {
    background: "#eff6ff",
    boxShadow: "inset 3px 0 0 #2563eb",
  },
  idCell: {
    fontSize: 13,
    fontWeight: 700,
    color: "#64748b",
  },
  envName: {
    fontSize: 15,
    fontWeight: 700,
    color: "#0f172a",
  },
  envKey: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  emptyState: {
    padding: 24,
    color: "#64748b",
    fontSize: 14,
  },
  error: {
    padding: "10px 14px",
    borderRadius: 12,
    background: "#fef2f2",
    color: "#b91c1c",
    fontSize: 14,
  },
  detailPanel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.05)",
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    padding: 20,
  },
  detailTitle: {
    margin: 0,
    fontSize: 22,
    fontWeight: 800,
    color: "#0f172a",
  },
  detailSubtitle: {
    marginTop: 6,
    marginBottom: 18,
    fontSize: 13,
    color: "#64748b",
  },
  sectionTitle: {
    margin: "0 0 10px",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "#64748b",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(140px, 180px) 1fr",
    gap: "10px 16px",
    marginBottom: 20,
    fontSize: 14,
  },
  detailLabel: {
    color: "#64748b",
  },
  detailValue: {
    color: "#0f172a",
    fontWeight: 600,
    wordBreak: "break-word",
  },
  currentBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 8px",
    borderRadius: 999,
    background: "#dcfce7",
    color: "#166534",
    fontSize: 12,
    fontWeight: 700,
    marginLeft: 8,
  },
  actionsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 12,
    borderTop: "1px solid #f1f5f9",
    marginTop: 8,
  },
  primaryButton: {
    border: "none",
    borderRadius: 10,
    padding: "9px 14px",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
};
