"""Platform Identity Store constants (technical keys only)."""

from __future__ import annotations

PLATFORM_IDENTITY_STATUS_ACTIVE = "active"
PLATFORM_IDENTITY_STATUS_SUSPENDED = "suspended"
PLATFORM_IDENTITY_STATUS_ARCHIVED = "archived"

PLATFORM_IDENTITY_STATUSES = frozenset(
    {
        PLATFORM_IDENTITY_STATUS_ACTIVE,
        PLATFORM_IDENTITY_STATUS_SUSPENDED,
        PLATFORM_IDENTITY_STATUS_ARCHIVED,
    }
)

PLATFORM_ROLE_OWNER = "platform_owner"
PLATFORM_ROLE_ADMIN = "platform_admin"
PLATFORM_ROLE_OPERATOR = "platform_operator"
PLATFORM_ROLE_SUPPORT = "platform_support"

PLATFORM_ROLES = frozenset(
    {
        PLATFORM_ROLE_OWNER,
        PLATFORM_ROLE_ADMIN,
        PLATFORM_ROLE_OPERATOR,
        PLATFORM_ROLE_SUPPORT,
    }
)

PLATFORM_ROLE_BINDING_STATUS_ACTIVE = "active"
PLATFORM_ROLE_BINDING_STATUS_SUSPENDED = "suspended"
PLATFORM_ROLE_BINDING_STATUS_REVOKED = "revoked"

PLATFORM_ROLE_BINDING_STATUSES = frozenset(
    {
        PLATFORM_ROLE_BINDING_STATUS_ACTIVE,
        PLATFORM_ROLE_BINDING_STATUS_SUSPENDED,
        PLATFORM_ROLE_BINDING_STATUS_REVOKED,
    }
)

CREDENTIAL_KIND_PASSWORD = "password"
CREDENTIAL_KIND_FEDERATED = "federated"
CREDENTIAL_KIND_PASSKEY = "passkey"
CREDENTIAL_KIND_MFA_TOTP = "mfa_totp"
CREDENTIAL_KIND_MFA_WEBAUTHN = "mfa_webauthn"

CREDENTIAL_KINDS = frozenset(
    {
        CREDENTIAL_KIND_PASSWORD,
        CREDENTIAL_KIND_FEDERATED,
        CREDENTIAL_KIND_PASSKEY,
        CREDENTIAL_KIND_MFA_TOTP,
        CREDENTIAL_KIND_MFA_WEBAUTHN,
    }
)

CREDENTIAL_PROVIDER_LOCAL = "local"
CREDENTIAL_PROVIDER_MICROSOFT = "microsoft"
CREDENTIAL_PROVIDER_GOOGLE = "google"
CREDENTIAL_PROVIDER_OIDC = "oidc"
CREDENTIAL_PROVIDER_SAML = "saml"

CREDENTIAL_STATUS_ACTIVE = "active"
CREDENTIAL_STATUS_DISABLED = "disabled"
CREDENTIAL_STATUS_REVOKED = "revoked"

CREDENTIAL_STATUSES = frozenset(
    {
        CREDENTIAL_STATUS_ACTIVE,
        CREDENTIAL_STATUS_DISABLED,
        CREDENTIAL_STATUS_REVOKED,
    }
)
