NOTIFICATION_CATEGORY_COMMENTS = "comments"
NOTIFICATION_CATEGORY_TASKS = "tasks"
NOTIFICATION_CATEGORY_DOCUMENTS = "documents"
NOTIFICATION_CATEGORY_WORKFLOW = "workflow"
NOTIFICATION_CATEGORY_SYSTEM = "system"
NOTIFICATION_CATEGORY_PROCESSES = "processes"

NOTIFICATION_PRIORITY_LOW = "low"
NOTIFICATION_PRIORITY_NORMAL = "normal"
NOTIFICATION_PRIORITY_HIGH = "high"
NOTIFICATION_PRIORITY_CRITICAL = "critical"

NOTIFICATION_TYPE_COMMENT_MENTION = "comment_mention"
NOTIFICATION_TYPE_COMMENT_REPLY = "comment_reply"
NOTIFICATION_TYPE_COMMENT_REACTION = "comment_reaction"

NOTIFICATION_TYPE_TASK_ASSIGNED = "task_assigned"
NOTIFICATION_TYPE_TASK_STATUS_CHANGED = "task_status_changed"
NOTIFICATION_TYPE_TASK_DUE_DATE_CHANGED = "task_due_date_changed"
NOTIFICATION_TYPE_TASK_ASSIGNEE_CHANGED = "task_assignee_changed"

NOTIFICATION_TYPE_PORTAL_INVITE = "portal_invite"

NOTIFICATION_TYPE_DOCUMENT_UPLOADED = "document_uploaded"
NOTIFICATION_TYPE_DOCUMENT_APPROVED = "document_approved"
NOTIFICATION_TYPE_DOCUMENT_REJECTED = "document_rejected"

NOTIFICATION_TYPE_WORKFLOW_REQUEST = "workflow_request"
NOTIFICATION_TYPE_WORKFLOW_APPROVED = "workflow_approved"
NOTIFICATION_TYPE_WORKFLOW_REJECTED = "workflow_rejected"

NOTIFICATION_TYPE_PROCESS_COMPLETED = "process_completed"
NOTIFICATION_TYPE_SYSTEM_ALERT = "system_alert"

ALLOWED_NOTIFICATION_CATEGORIES = {
    NOTIFICATION_CATEGORY_COMMENTS,
    NOTIFICATION_CATEGORY_TASKS,
    NOTIFICATION_CATEGORY_DOCUMENTS,
    NOTIFICATION_CATEGORY_WORKFLOW,
    NOTIFICATION_CATEGORY_SYSTEM,
    NOTIFICATION_CATEGORY_PROCESSES,
}

ALLOWED_NOTIFICATION_PRIORITIES = {
    NOTIFICATION_PRIORITY_LOW,
    NOTIFICATION_PRIORITY_NORMAL,
    NOTIFICATION_PRIORITY_HIGH,
    NOTIFICATION_PRIORITY_CRITICAL,
}