export const controlPlaneStyles = {
  page: {
    flex: 1,
    minHeight: 0,
    height: "100%",
    padding: "8px 12px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    boxSizing: "border-box",
    background: "#F8FAFC",
    overflowY: "auto",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  },
  kicker: {
    fontSize: 13,
    fontWeight: 700,
    color: "#7c3aed",
    marginBottom: 6,
  },
  title: {
    margin: 0,
    fontSize: 24,
    color: "#0f172a",
  },
  subtitle: {
    margin: "8px 0 0",
    fontSize: 14,
    color: "#64748b",
    maxWidth: 760,
  },
  card: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 20,
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.04)",
  },
  metricsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 12,
  },
  metricCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: "12px 14px",
    background: "#f8fafc",
  },
  metricLabel: {
    fontSize: 12,
    color: "#64748b",
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 700,
    color: "#0f172a",
  },
  filtersRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "flex-end",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 160,
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: "#475569",
  },
  input: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    background: "#fff",
    color: "#0f172a",
  },
  select: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    background: "#fff",
    color: "#0f172a",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 14,
  },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    borderBottom: "1px solid #e2e8f0",
    color: "#475569",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid #f1f5f9",
    color: "#0f172a",
    verticalAlign: "middle",
  },
  linkButton: {
    border: "none",
    background: "transparent",
    color: "#2563eb",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
  },
  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 16px",
    background: "#fff",
    color: "#0f172a",
    fontWeight: 600,
    cursor: "pointer",
  },
  error: {
    color: "#b91c1c",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 10,
    padding: "10px 12px",
    marginBottom: 12,
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "180px 1fr",
    gap: "12px 20px",
    alignItems: "start",
  },
  detailLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "#64748b",
  },
  detailValue: {
    fontSize: 14,
    color: "#0f172a",
    lineHeight: 1.5,
  },
  futureHint: {
    marginTop: 16,
    padding: "12px 14px",
    borderRadius: 12,
    background: "#f5f3ff",
    border: "1px solid #ddd6fe",
    color: "#5b21b6",
    fontSize: 13,
    lineHeight: 1.5,
  },
};
